version: '1'
services:
  microservice:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - spring.datasource.url=jdbc:oracle:thin:@ckvy7suy33qb5huu_tp?TNS_ADMIN=/app/oracle_wallet/
      - spring.datasource.username=PRODUCTAPI
      - spring.datasource.password=!&fddE>X1hMagb3
      
    restart: always